version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres-server
    hostname: postgres-server
    restart: unless-stopped
    
    environment:
      # PostgreSQL superuser password
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      
      # PostgreSQL superuser name (default: postgres)
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      
      # Default database name (optional)
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      
      # Timezone (optional)
      - TZ=${TZ:-UTC}
      
      # PostgreSQL configuration (optional)
      # Enable logging for better debugging
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --locale=C
    
    ports:
      # Map container port 5432 to host port 5432
      # Format: "host_port:container_port"
      - "${POSTGRES_PORT:-5432}:5432"
    
    volumes:
      # Persist database data
      - postgres_data:/var/lib/postgresql/data
      # Optional: Mount custom SQL scripts to initialize database
      # - ./postgres-init-scripts:/docker-entrypoint-initdb.d
    
    networks:
      - postgres-network
    
    # Resource limits (optional but recommended)
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G
    
    # Health check to ensure container is ready
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
    driver: local
    name: postgres_data

networks:
  postgres-network:
    driver: bridge
    name: postgres-network

