version: '3.8'

services:
  redis:
    image: redis:8-alpine
    container_name: redis-server
    hostname: redis-server
    restart: unless-stopped
    
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD:-redis}
      --save 60 1
      --loglevel warning
      --appendonly yes
    
    environment:
      # Timezone (optional)
      - TZ=${TZ:-UTC}
    
    ports:
      # Map container port 6379 to host port 6379
      # Format: "host_port:container_port"
      - "${REDIS_PORT:-6379}:6379"
    
    volumes:
      # Persist Redis data
      - redis_data:/data
      # Optional: Mount custom Redis configuration file
      # - ./redis.conf:/usr/local/etc/redis/redis.conf
    
    networks:
      - redis-network
    
    # Resource limits (optional but recommended)
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    
    # Health check to ensure container is ready
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD:-redis} ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  redis_data:
    driver: local
    name: redis_data

networks:
  redis-network:
    driver: bridge
    name: redis-network

